version: '3.9'

services:
  app:
    build: .
    container_name: kaizen_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:changeme=
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kaizen
      DB_USERNAME: kaizen_user
      DB_PASSWORD: secret
    depends_on:
      - db

  web:
    image: nginx:stable
    container_name: kaizen_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kaizen_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kaizen
      MYSQL_USER: kaizen_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
